const button_1 = document.querySelector('#button1');
const button_2 = document.querySelector('#button2');
const button_3 = document.querySelector('#button3');

const checkButton = document.querySelector('#s');
const checkButton2 = document.querySelector('#s2');
const checkButton3 = document.querySelector('#s3');

const description = document.querySelector('.description');
const question = document.querySelector('.question');
const question_number = document.querySelector('.problem-number');
const card = document.querySelector('#cards');

const answerInput = document.querySelector('.input-answer');
const answerInput2 = document.querySelector('.input-answer2');
const answerInput3 = document.querySelector('.input-answer3');

const p1 = document.querySelector('.p1');
const p2 = document.querySelector('.p2');

let number;

const hide = document.querySelector('.answer');
const hideMain = document.querySelector('.main-content');
const card2 = document.querySelector('.replacer');

card2.style.display = 'none';

button_1.onclick = problem_1;
button_2.onclick = problem_2;
button_3.onclick = problem_3;

function problem_1() 
{
  question.innerHTML = "<b>Multiples of 3 of 5</b>";
  question_number.innerHTML = "<b>Problem 1</b>";
  description.innerHTML = "If we list all the natural numbers below <b>10</b> that are multiples " +
  "of <b>3</b> or <b>5</b>, we get <b>3</b>, <b>5</b>, <b>6</b> and <b>9</b>. The sum of these multiples is <b>23</b>.<br><br>" +
  "Find the sum of all the multiples of <b>3</b> or <b>5</b> below <b>1000</b>";

  hideMain.classList.remove('d-none');
  hide.classList.remove('d-none');
  card2.style.display = 'none';

  $('#s2').hide();
  $('#s3').hide();
  $('#s').show();
  $('.p2').show();
  $('.p1').show();
}

function problem_2() 
{
  question.innerHTML = "<b>Even Fibonacci Numbers</b>";
  question_number.innerHTML = "<b>Problem 2</b>";
  description.innerHTML = "Each new term in the Fibonacci sequence is generated by adding " +
    "the previous two terms. By starting with <b>1</b> and <b>2</b>, the first <b>10</b> terms will be:<br><br>" +
    "<b>1, 2, 3, 5, 8, 1, 21, 34, 55, 89</b>,...<br><br>" +
    "By considering the terms in the Fibonacci sequence whose values do not exceed four million," +
    " find the sum of the even-valued terms.";

  hideMain.classList.remove('d-none');
  hide.classList.remove('d-none');
  card2.style.display = 'none';

  $('#s').hide();
  $('#s3').hide();
  $('#s2').show();
  $('.p2').show();
  $('.p1').show();
}

function problem_3() 
{
  question.innerHTML = "<b>Largest Prime Factor</b>";
  question_number.innerHTML = "<b>Problem 3</b>";
  description.innerHTML = "The prime factors of <b>13195</b> are <b>5, 7, 13</b> and <b>29</b>.<br><br>" +
  "What is the largest prime factor of the number <b>600851475143</b>?";

  hideMain.classList.remove('d-none');
  hide.classList.remove('d-none');  
  card2.style.display = 'none';

  
  $('#s3').show();
  $('#s2').hide();
  $('#s').hide();
  $('.p1').hide();
  $('.p2').hide();
}

checkButton.addEventListener('click', function() 
{
  let totalSum = 0;
  let answer = answerInput.value; 
  let answer2 = answerInput2.value;
  let answer3 = answerInput3.value;
  
  for (let i = 1; i < answer; i++) 
  {
    if (i % answer2 === 0 || i % answer3 === 0) 
    {
      totalSum = totalSum + i;
    }
  }

  if (answer != '')
    {
      Swal.fire("Good job!", "Congratulations!", "success");
      hide.classList.add('d-none');
      card2.style.display = 'block';
      card.innerHTML = totalSum;
    }
    else
    {
      Swal.fire("Oops!", "That's the wrong answer. Try Again", "error");
    }
});

checkButton2.addEventListener('click', function() 
{
  let sum = 0;
  let temp;

  let answer = parseInt(answerInput.value);
  let answer2 = parseInt(answerInput2.value); 
  let answer3 = parseInt(answerInput3.value); 

  while (answer3 < answer) 
  {
    if (answer3 % 2 === 0) 
    {
        sum += answer3;
    }
      temp = answer2 + answer3;
      answer2 = answer3;
      answer3 = temp;
  }

  console.log(answer);
  console.log(answer2);
  console.log(answer3);

  // 4613732
  if (answer != '')
    {
      Swal.fire("Good job!", "Congratulations!", "success");
      hide.classList.add('d-none');
      card2.style.display = 'block';
      card.innerHTML = sum;
    }
    else
    {
      Swal.fire("Oops!", "That's the wrong answer. Try Again", "error");
    }
});

checkButton3.addEventListener('click', function() 
{
  var largestPrimeFactor = 0;
  var i = 2;
  let answer = answerInput.value;

  while (i <= answer) 
  {
    if (answer % i === 0) 
    {
      largestPrimeFactor = i;
      answer /= i;
    } 
    else 
    {
      i++;
    }
  }
  console.log("Q3");
  number = largestPrimeFactor;

  if (answer != '')
    {
      Swal.fire("Good job!", "Congratulations!", "success");
      hide.classList.add('d-none');
      card2.style.display = 'block';
      card.innerHTML = number;
    }
    else
    {
      Swal.fire("Oops!", "That's the wrong answer. Try Again", "error");
    }

});
